version: '3'

services:
  notebook:
    build: .
    command: jupyter notebook --ip=0.0.0.0 --port=8888
    volumes:
      - .:/app
    ports:
      - "8899:8888"
  ml:
    build: .
    command: python3
    volumes:
      - .:/app
    ports:
      - "8809:8899"
    